services:

  simplesamlphp:
    build:
      context: .
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
    environment:
      DEBUG: "true"
      SIMPLESAMLPHP_PATH: "/simplesamlphp"
      SIMPLESAMLPHP_ADMIN_PASSWORD: "password"
      SIMPLESAMLPHP_DEBUG_SAML: "true"
      SIMPLESAMLPHP_LOG_LEVEL: "DEBUG"
      SIMPLESAMLPHP_ENABLE_DEFAULT_VHOST: "true"
      SIMPLESAMLPHP_INTERNAL_PROXY_HOSTNAME: "traefik.${INTERNAL_DOMAIN:-internal.test}"
      SIMPLESAMLPHP_SP_NAME: "sp-test"
      SIMPLESAMLPHP_SIGN_AUTHN_REQUESTS: "true"
      SIMPLESAMLPHP_SIGN_LOGOUT_REQUESTS: "true"
      SIMPLESAMLPHP_SIGN_REDIRECTS_REQUESTS: "true"
      SIMPLESAMLPHP_ENCRYPTED_ASSERTIONS: "true"
      SIMPLESAMLPHP_SP_IDP_ID: "https://keycloak.${EXTERNAL_DOMAIN:-external.test}/auth/realms/master"
      SIMPLESAMLPHP_SP_IDP_METADATA_URL: "https://keycloak.${EXTERNAL_DOMAIN:-external.test}/auth/realms/master/protocol/saml/descriptor"
      SIMPLESAMLPHP_CA_FILE: "/etc/simplesamlphp/ca/rootCA.pem"
      MSMTP_HOST: "mail.${INTERNAL_DOMAIN:-internal.test}"
      MSMTP_FROM: "no-reply@simplesamlphp.${EXTERNAL_DOMAIN:-external.test}"
    volumes:
      - "./overlay/etc/entrypoint.d:/etc/entrypoint.d"
      - "./overlay/etc/server.d:/etc/server.d"
      - "./overlay/usr/bin/entrypoint:/usr/bin/entrypoint"
      - "./overlay/usr/bin/server:/usr/bin/server"
      - "./overlay/usr/bin/simplesamlphp-get-sp-metadata:/usr/bin/simplesamlphp-get-sp-metadata"
      - "./overlay/usr/share/simplesamlphp/config-templates/apache2.conf:/usr/share/simplesamlphp/config-templates/apache2.conf"
      - "./overlay/usr/share/simplesamlphp/config-templates/trust-forwarded-headers.php:/usr/share/simplesamlphp/config-templates/trust-forwarded-headers.php"
      - "./overlay/usr/share/simplesamlphp/cli.metadata-converter.php:/usr/share/simplesamlphp/cli.metadata-converter.php"
      - "./overlay/var/tmp/patches/simplesamlphp:/var/tmp/patches/simplesamlphp"
      - "./traefik-data/ca:/etc/simplesamlphp/ca"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.simplesamlphp.loadbalancer.server.port=80"
      - "traefik.http.routers.simplesamlphp.rule=Host(`simplesamlphp.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.simplesamlphp.entrypoints=websecure"
      - "traefik.http.routers.simplesamlphp.tls=true"

  traefik:
    entrypoint: /etc/entrypoint/entrypoint.sh
    command:
      - "--"
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
      - --serverstransport.rootcas=$${CAROOT}/rootCA.pem
      - --api.dashboard=true
      - --providers.file.directory=/etc/traefik/conf/dynamic-config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.watch=true
      - --providers.docker.defaultRule=Host(`{{ .Name }}.${EXTERNAL_DOMAIN:-external.test}`)
      - --log.level=INFO
      - --log.format=json
    environment:
      - CAROOT=${CAROOT:-/etc/traefik/ssl/ca}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/etc/entrypoint"
      - traefik:/etc/traefik
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    hostname: "traefik.${INTERNAL_DOMAIN:-internal.test}"
    networks:
      default:
        aliases:
          - "traefik.${EXTERNAL_DOMAIN:-external.test}"
          - "keycloak.${EXTERNAL_DOMAIN:-external.test}"
          - "simplesamlphp.${EXTERNAL_DOMAIN:-external.test}"
          - "mail.${EXTERNAL_DOMAIN:-external.test}"
          - "traefik.${INTERNAL_DOMAIN:-internal.test}"
    labels:
      - "traefik.enable=true"
      # Global redirect http to https
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@file"
      # Access API enpoint through traefik itself
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.options=myTLSOptions@file"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboardAuth@file"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    entrypoint:
      - '/bin/bash'
      - '-c'
      - '/opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start --optimized --verbose'
    environment:
      # Database
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb.${INTERNAL_DOMAIN:-internal.test}
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=password
      # Master Realm + Admin user
      - KC_REALM_NAME=master
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      # Hostname
      - KC_HOSTNAME=keycloak.${EXTERNAL_DOMAIN:-external.test}
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_HOSTNAME_STRICT=false
      # HTTP
      - KC_HTTP_ENABLED=true
      - KC_HTTP_HOST=0.0.0.0
      - HTTP_ADDRESS_FORWARDING=true
      # PROXY
      - KC_PROXY=edge
      - KC_PROXY_HEADERS=xforwarded
      - PROXY_ADDRESS_FORWARDING=true
      # Log level
      - KC_LOG_LEVEL=info
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keycloak-saml:/data/keycloak-saml/:ro
    depends_on:
      - mariadb
    hostname: keycloak.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - keycloak.${INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"

  mariadb:
    image: mariadb:10.4.13
    volumes:
      - ./keycloak-data/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
# https://github.com/docker-library/mariadb/issues/261
# https://github.com/docker-library/mariadb/issues/262
      - MYSQL_INITDB_SKIP_TZINFO=true
    hostname: mariadb.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb.${INTERNAL_DOMAIN:-internal.test}

  mail:
    image: maildev/maildev:1.1.0
    environment:
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    hostname: mail.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - "mail.${INTERNAL_DOMAIN:-internal.test}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mail.loadbalancer.server.port=80"
      - "traefik.http.routers.mail.rule=Host(`mail.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.tls=true"
  
volumes:
  traefik:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/traefik
