services:

  simplesamlphp:
    build:
      context: .
    entrypoint:
      - '/bin/sh'
      - '-c'
      - |
        if [ ! -f "/usr/local/share/ca-certificates/dev.crt" ]; then
          if [ -f "$${CAROOT}/rootCA.pem" ]; then
        cp $${CAROOT}/rootCA.pem /usr/local/share/ca-certificates/dev.crt;
        update-ca-certificates;
          fi
        fi
        # To develop comment out next line
        /usr/local/bin/entrypoint /usr/local/bin/server
        # To develop uncomment next line 
        #/bin/bash
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
    environment:
      TZ: "Europe/Madrid"
      DEBUG: "true"
      APACHE2_REMOTEIP_TRUSTPROXY_HOSTNAME: "traefik.${INTERNAL_DOMAIN:-internal.test}"
      SIMPLESAMLPHP_ENABLE_GLOBAL: "true"
      SIMPLESAMLPHP_ENABLE_VHOST: "000-default"
      SIMPLESAMLPHP_BASEURLPATH: "https://simplesamlphp.${EXTERNAL_DOMAIN:-external.test}/simplesamlphp/"
      SIMPLESAMLPHP_ADMIN_PASSWORD: "password"
      SIMPLESAMLPHP_DEBUG_SAML: "true"
      SIMPLESAMLPHP_LOG_LEVEL: "DEBUG"
      SIMPLESAMLPHP_SP_NAME: "sp-test"
      SIMPLESAMLPHP_SIGN_AUTHN_REQUESTS: "true"
      SIMPLESAMLPHP_SIGN_LOGOUT_REQUESTS: "true"
      SIMPLESAMLPHP_SIGN_REDIRECTS_REQUESTS: "true"
      SIMPLESAMLPHP_ENCRYPTED_ASSERTIONS: "true"
      SIMPLESAMLPHP_SP_IDP_ID: "https://sso.${EXTERNAL_DOMAIN:-external.test}/realms/master"
      SIMPLESAMLPHP_SP_IDP_METADATA_URL: "https://sso.${EXTERNAL_DOMAIN:-external.test}/realms/master/protocol/saml/descriptor"
      MSMTP_HOST: "mail.${INTERNAL_DOMAIN:-internal.test}"
      MSMTP_FROM: "no-reply@simplesamlphp.${EXTERNAL_DOMAIN:-external.test}"
      MSMTP_PORT: 1025
      # Development
      SIMPLESAMLPHP_CA_FILE: "${CAROOT:-/etc/traefik/ssl/ca}/rootCA.pem"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Development
      - "./overlay/etc/entrypoint:/etc/entrypoint"
      - "./overlay/etc/server:/etc/server"
      - "./overlay/usr/local/bin/entrypoint:/usr/local/bin/entrypoint"
      - "./overlay/usr/local/bin/server:/usr/local/bin/server"
      - "./overlay/usr/local/bin/simplesamlphp-get-sp-metadata:/usr/local/bin/simplesamlphp-get-sp-metadata"
      - "./overlay/usr/local/bin/wait-for:/usr/local/bin/wait-for"
      - "./overlay/usr/share/simplesamlphp/config-templates/apache2.conf:/usr/share/simplesamlphp/config-templates/apache2.conf"
      - "./overlay/usr/share/simplesamlphp/config-templates/trust-forwarded-headers.php:/usr/share/simplesamlphp/config-templates/trust-forwarded-headers.php"
      - "./overlay/usr/share/simplesamlphp/cli-metadata-converter.php:/usr/share/simplesamlphp/cli-metadata-converter.php"
      - "./overlay/var/tmp/patches/simplesamlphp:/var/tmp/patches/simplesamlphp"
      - apache2-etc:/etc/apache2
      - simplesamlphp-etc:/etc/simplesamlphp
      - traefik:/etc/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.simplesamlphp.loadbalancer.server.port=80"
      - "traefik.http.routers.simplesamlphp.rule=Host(`simplesamlphp.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.simplesamlphp.entrypoints=websecure"
      - "traefik.http.routers.simplesamlphp.tls=true"

  traefik:
    image: traefik:3.1.7
    entrypoint: /etc/entrypoint/entrypoint.sh
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
      - --serverstransport.rootcas=$${CAROOT}/rootCA.pem
      - --api.dashboard=true
      - --providers.file.directory=/etc/traefik/conf/dynamic-config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.watch=true
      - --providers.docker.defaultRule=Host(`{{ .Name }}.${EXTERNAL_DOMAIN:-external.test}`)
      - --log.level=INFO
      - --log.format=json
    environment:
      - CAROOT=${CAROOT:-/etc/traefik/ssl/ca}
      - DNS_SERVERS=${DNS_SERVERS:-8.8.8.8 8.8.4.4}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/etc/entrypoint"
      - traefik:/etc/traefik
      - development:/development
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    hostname: "traefik.${INTERNAL_DOMAIN:-internal.test}"
    networks:
      default:
        aliases:
          - "traefik.${EXTERNAL_DOMAIN:-external.test}"
          - "sso.${EXTERNAL_DOMAIN:-external.test}"
          - "simplesamlphp.${EXTERNAL_DOMAIN:-external.test}"
          - "mail.${EXTERNAL_DOMAIN:-external.test}"
          - "traefik.${INTERNAL_DOMAIN:-internal.test}"
    labels:
      - "traefik.enable=true"
      # Global redirect http to https
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@file"
      # Access API enpoint through traefik itself
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.options=myTLSOptions@file"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboardAuth@file"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    entrypoint:
      - '/bin/bash'
      - '-c'
      - |
        find /development/ext -type f -iname '*.jar' -exec cp {} /opt/keycloak/providers \; ;
        /opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start --optimized --verbose
    environment:
      # Database
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb.${INTERNAL_DOMAIN:-internal.test}
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=password
      # Master Realm + Admin user
      - KC_REALM_NAME=master
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      # Hostname
      - KC_HOSTNAME=sso.${EXTERNAL_DOMAIN:-external.test}
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_HOSTNAME_STRICT=false
      # HTTP
      - KC_HTTP_ENABLED=true
      - KC_HTTP_HOST=0.0.0.0
      - HTTP_ADDRESS_FORWARDING=true
      # PROXY
      - KC_PROXY=edge
      - KC_PROXY_HEADERS=xforwarded
      - PROXY_ADDRESS_FORWARDING=true
      # Log level
      - KC_LOG_LEVEL=info
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keycloak:/scripts/keycloak/:ro
      - development:/development
    depends_on:
      - mariadb
      - traefik
    hostname: sso.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - sso.${INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sso.loadbalancer.server.port=8080"
      - "traefik.http.routers.sso.rule=Host(`sso.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.sso.entrypoints=websecure"
      - "traefik.http.routers.sso.tls=true"

  mariadb:
    image: mariadb:10.11.9
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - keycloak-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    hostname: mariadb.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb.${INTERNAL_DOMAIN:-internal.test}

  mail:
    image: maildev/maildev:2.1.0
    # Fix: https://github.com/maildev/maildev/issues/484#issuecomment-2015490293
    healthcheck:
      test: 'wget -O - http://127.0.0.1:$${MAILDEV_WEB_PORT}$${MAILDEV_BASE_PATHNAME}/healthz || exit 1'
    hostname: mail.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - "mail.${INTERNAL_DOMAIN:-internal.test}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mail.loadbalancer.server.port=1080"
      - "traefik.http.routers.mail.rule=Host(`mail.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.tls=true"

  whoami:
    image: traefik/whoami
    hostname: whoami.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - "whoami.${INTERNAL_DOMAIN:-internal.test}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"

  dns:
    image: coredns/coredns:1.11.4
    command: -conf /development/coredns/Corefile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - development:/development
    ports:
      - "${DNS_BIND_IP:-127.1.1.1}:53:53/udp"
    hostname: dns.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - "dns.${INTERNAL_DOMAIN:-internal.test}"

volumes:
  traefik:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/traefik
  development:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/development
  keycloak-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/keycloak/mariadb
  apache2-etc:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/apache2
  simplesamlphp-etc:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/simplesamlphp