version: '3.7'

services:

  simplesamlphp:
    build:
      context: .
    entrypoint: /bin/bash
#    command: /bin/bash
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
    environment:
      DEBUG: "true"
      SIMPLESAMLPHP_PATH: "/simplesamlphp"
      SIMPLESAMLPHP_ADMIN_PASSWORD: "password"
      SIMPLESAMLPHP_DEBUG_SAML: "true"
      SIMPLESAMLPHP_LOG_LEVEL: "DEBUG"
      SIMPLESAMLPHP_ENABLE_DEFAULT_VHOST: "true"
      SIMPLESAMLPHP_INTERNAL_PROXY_HOSTNAME: "traefik.${INTERNAL_DOMAIN:-internal.test}"
      SIMPLESAMLPHP_SP_NAME: "sp-test"
      SIMPLESAMLPHP_SIGN_AUTHN_REQUESTS: "true"
      SIMPLESAMLPHP_SIGN_LOGOUT_REQUESTS: "true"
      SIMPLESAMLPHP_SIGN_REDIRECTS_REQUESTS: "true"
      SIMPLESAMLPHP_ENCRYPTED_ASSERTIONS: "true"
      SIMPLESAMLPHP_SP_IDP_ID: "https://keycloak.${EXTERNAL_DOMAIN:-external.test}/auth/realms/master"
      SIMPLESAMLPHP_SP_IDP_METADATA_URL: "https://keycloak.${EXTERNAL_DOMAIN:-external.test}/auth/realms/master/protocol/saml/descriptor"
      SIMPLESAMLPHP_CA_FILE: "/etc/simplesamlphp/ca/rootCA.pem"
      MSMTP_HOST: "mail.${INTERNAL_DOMAIN:-internal.test}"
      MSMTP_FROM: "no-reply@simplesamlphp.external.test"
    volumes:
      - "./overlay/etc/entrypoint.d:/etc/entrypoint.d"
      - "./overlay/etc/server.d:/etc/server.d"
      - "./overlay/usr/bin/entrypoint:/usr/bin/entrypoint"
      - "./overlay/usr/bin/server:/usr/bin/server"
      - "./overlay/usr/bin/simplesamlphp-get-sp-metadata:/usr/bin/simplesamlphp-get-sp-metadata"
      - "./overlay/usr/share/simplesamlphp/config-templates/apache2.conf:/usr/share/simplesamlphp/config-templates/apache2.conf"
      - "./overlay/usr/share/simplesamlphp/config-templates/trust-forwarded-headers.php:/usr/share/simplesamlphp/config-templates/trust-forwarded-headers.php"
      - "./overlay/usr/share/simplesamlphp/cli.metadata-converter.php:/usr/share/simplesamlphp/cli.metadata-converter.php"
      - "./overlay/var/tmp/patches:/var/tmp/patches"
      - "./traefik-data/ca:/etc/simplesamlphp/ca"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.simplesamlphp.loadbalancer.server.port=80"
      - "traefik.http.routers.simplesamlphp.rule=Host(`simplesamlphp.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.simplesamlphp.entrypoints=websecure"
      - "traefik.http.routers.simplesamlphp.tls=true"

  traefik:
    image: traefik:2.2.11
    entrypoint:
      - '/bin/sh'
      - '-c'
      - |
        if [[ ! -e "$${CAROOT}/rootCA.pem" ]]; then
          if [[ ! -d "$${CAROOT}" ]]; then
            mkdir -p "$${CAROOT}";
          fi;

          # mkcert installation
          wget -O /tmp/mkcert -q $${MKCERT_DOWNLOAD_URL};
          echo "$${MKCERT_SHA256}  /tmp/mkcert" | sha256sum -c -w -s -;
          mv /tmp/mkcert /usr/local/bin;
          chmod +x /usr/local/bin/mkcert;

          # generate ca
          mkdir -p $${CAROOT};
          mkcert --install;

          echo "Development CA certificate, beware !";
          cat $$(mkcert -CAROOT)/rootCA.pem;
        fi;

        if [[ ! -e "/etc/traefik/ssl/traefik-key.pem" ]]; then
          if [[ ! -d "/etc/traefik/ssl" ]]; then
            # generate "localhost certificate"
            mkdir -p /etc/traefik/ssl;
          fi;

          mkcert -cert-file /etc/traefik/ssl/traefik.pem -key-file /etc/traefik/ssl/traefik-key.pem "localhost" "127.0.0.1" "::1";
          cp /etc/traefik/ssl/traefik.pem /etc/traefik/ssl/traefik-fullchain.pem;
          cat $$(mkcert -CAROOT)/rootCA.pem >> /etc/traefik/ssl/traefik-fullchain.pem;
        fi;

        mkdir -p /etc/traefik/conf/dynamic-config;
        cat << EOF > /etc/traefik/conf/dynamic-config/file-provider.toml
        [[tls.certificates]]
          certFile = "/etc/traefik/ssl/traefik-fullchain.pem"
          keyFile = "/etc/traefik/ssl/traefik-key.pem"
          stores = ["default"]

        [tls.stores]
          [tls.stores.default]
            [tls.stores.default.defaultCertificate]
              certFile = "/etc/traefik/ssl/traefik-fullchain.pem"
              keyFile  = "/etc/traefik/ssl/traefik-key.pem"

        [tls.options]
          [tls.options.default]
            minVersion = "VersionTLS12"
          [tls.options.myTLSOptions]
            minVersion = "VersionTLS13"

        [http.middlewares]
          [http.middlewares.dashboardAuth.basicAuth]
            # admin:password
            users = [
              "admin:\$$apr1\$$97xk9Kkr\$$gavbmzhrI6uOVYNOfYByQ/"
            ]
          [http.middlewares.redirect-to-https.redirectScheme]
            scheme = "https"
            permanent = true
        EOF
        exec /entrypoint.sh "$$@"
    command:
      - "--"
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
      - --serverstransport.rootcas=$${CAROOT}/rootCA.pem
      - --api.dashboard=true
      - --providers.file.directory=/etc/traefik/conf/dynamic-config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.watch=true
      - --providers.docker.defaultRule=Host(`{{ .Name }}.${EXTERNAL_DOMAIN:-external.test}`)
      - --log.level=INFO
      - --log.format=json
    environment:
      - MKCERT_VERSION=${MKCERT_VERSION:-v1.4.1}
      - MKCERT_DOWNLOAD_URL=https://github.com/FiloSottile/mkcert/releases/download/${MKCERT_VERSION:-v1.4.1}/mkcert-${MKCERT_VERSION:-v1.4.1}-linux-amd64
      - MKCERT_SHA256=${MKCERT_SHA256SUM:-e116543bfabb4d88010dda8a551a5d01abbdf9b4f2c949c044b862365038f632}
      - CAROOT=/etc/traefik/ca
    volumes:
      - "./traefik-data/ca:/etc/traefik/ca"
      - "./traefik-data/ssl:/etc/traefik/ssl"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    hostname: "traefik.${INTERNAL_DOMAIN:-internal.test}"
    networks:
      default:
        aliases:
          - "traefik.${INTERNAL_DOMAIN:-internal.test}"
          - "traefik.${EXTERNAL_DOMAIN:-external.test}"
          - "keycloak.${EXTERNAL_DOMAIN:-external.test}"
          - "simplesamlphp.${EXTERNAL_DOMAIN:-external.test}"
          - "mail.${EXTERNAL_DOMAIN:-external.test}"
    labels:
      - "traefik.enable=true"
      # Global redirect http to https
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@file"
      # Access API enpoint through traefik itself
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.options=myTLSOptions@file"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboardAuth@file"

  keycloak:
    image: jboss/keycloak:10.0.2
    entrypoint:
      - '/bin/bash'
      - '-c'
      - '/opt/jboss/tools/docker-entrypoint.sh $$@'
    command:
      - "--"
      - "-b 0.0.0.0"
    environment:
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb.${INTERNAL_DOMAIN:-internal.test}
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
    hostname: keycloak.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - keycloak.${INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"

  mariadb:
    image: mariadb:10.4.13
    volumes:
      - ./keycloak-data/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
# https://github.com/docker-library/mariadb/issues/261
# https://github.com/docker-library/mariadb/issues/262
      - MYSQL_INITDB_SKIP_TZINFO=true
    hostname: mariadb.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb.${INTERNAL_DOMAIN:-internal.test}

  mail:
    image: maildev/maildev:1.1.0
    environment:
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    hostname: mail.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - "mail.${INTERNAL_DOMAIN:-internal.test}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mail.loadbalancer.server.port=80"
      - "traefik.http.routers.mail.rule=Host(`mail.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.tls=true"